### ISSUE TITLE
No Forge version found for 1.12.1

### ISSUE THREAD

**Issue by rosareven** [dizzyd/mcdex#12] opened 2017-09-08 06:19 UTC
I just tried to pack.create a new pack for MC version 1.12.1, but it came back with no forge version found.

1.12 works. Does Mcdex only detect stable Forge version?

![capture](https://user-images.githubusercontent.com/17244066/30198499-6521bbd4-94b1-11e7-82d0-c3b46f7b9982.PNG)

**Comment by dizzyd** [comment] 2017-09-11 01:06
Hi @rosareven - there is a bug in how the database is being generated. I'm investigating and hope to have a fix in next few days. :)

**Comment by dizzyd** [comment] 2017-09-11 13:14
Hi @rosareven - I was wrong, the database was fine. :) The problem is that if you choose a version of Forge that is not recommended, such as 1.12.1, you need to be more explicit.

So, try this:

> C:\\>mcdex forge.list 1.12.1
> 14.22.0.2475 (latest)

Then:
> C:\\> mcdex pack.create Backpacker 1.12.1 14.22.0.2475

Let me know if that works for you! :)

**Comment by OrdinatorStouff** [comment] 2017-09-22 19:57
I was able to install 1.12.2 forge 14.23.0.2489 this way -- it just only defaults to RBs not latest which you could say is a feature not a bug.

**Comment by dizzyd** [comment] 2017-09-24 15:08
I'm closing this issue since there aren't any further comments. :)

**Closed by dizzyd** 2017-09-24 15:08 UTC

**Comment by rosareven** [comment] 2017-10-06 04:43
Hi there, I'm so sorry I have been away and only just test this out now, this time with 1.12.2 MC version and an attempt at latest version of forge. Unfortunately it doesn't want to recognise the latest version still, only the latest stable.

![image](https://user-images.githubusercontent.com/17244066/31263300-1228be8e-aaad-11e7-84bd-3ec0188e7cb0.png)
